import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

import { routing } from '@/i18n/routing';

import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default async function RootLayout({
	children,
	params
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;

	if (!routing.locales.includes(locale)) {
		notFound();
	}

	return (
		<html lang={locale}>
			<body>{children}</body>
		</html>
	);
}
